spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/socket_chat
    username: root
    password: rud10241024@
  properties:
    hibernate:
    #default_batch_fetch_size: 1000
file:
  user:
    profileDir: C:\Users\ruddh\Pictures\image\
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
